# Generated by Django 4.2.11 on 2024-05-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restraun", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="guest_number",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="last_name",
        ),
        migrations.AddField(
            model_name="booking",
            name="reservation_date",
            field=models.DateField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="reservation_slot",
            field=models.SmallIntegerField(default=10),
        ),
    ]
