# Generated by Django 4.2.11 on 2024-05-06 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "restraun",
            "0002_remove_booking_comment_remove_booking_guest_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="reservation_date",
            field=models.DateField(
                default=datetime.date.today, help_text="Enter date in YYYY-MM-DD format"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
